export type GlobeDisplayMode
  = | 'terrain'
    | 'biomes'
    | 'elevation'
    | 'contours'
    | 'plates'
    | 'trade'
    | 'cultures'
    | 'religions'
    | 'polities'

export interface GlobeGenParams {
  seed: number
  subdivision: number
  planetRadius: number
  plateCount: number
  continentCount: number
  landCoverage: number
  sizeVariety: number
  spread: number
  compactness: number
  elongation: number
  coastlineRoughness: number
  islandCount: number
  islandLandShare: number
  islandClustering: number
  islandTectonicBias: number
  mountainStrength: number
  noiseStrength: number
  equatorTemperature: number
  poleTemperature: number
  latitudeTemperatureExponent: number
  axialTilt: number
  elevationLapseRate: number
  temperatureNoiseStrength: number
  windPerturbation: number
  oceanCurrentStrength: number
  oceanHeatTransport: number
  oceanEvaporation: number
  landEvaporation: number
  moistureIterations: number
  moistureRetention: number
  basePrecipitation: number
  equatorialRainStrength: number
  subtropicalDryness: number
  midlatitudeRainStrength: number
  orographicStrength: number
  evapotranspirationStrength: number
  infiltration: number
  lakeDensity: number
  lakeMinDepth: number
  lakeMinRegionCount: number
  lakeMinCoastDistance: number
  lakeMaxLandCoverage: number
  lakeEvaporationStrength: number
  lakeOverflowThreshold: number
  lakeMinFillRatio: number
  riverBasinThreshold: number
  riverMinSourceElevation: number
  riverMinLength: number
  settlementDensity: number
  cultureCount: number
  culturalBlending: number
  religionCount: number
  religiousProselytism: number
  polityCount: number
  politicalCohesion: number
  roadDensity: number
  shippingRouteDensity: number
  shippingMaxRange: number
  shippingCurrentInfluence: number
  shippingWindInfluence: number
  shippingOpenOceanRisk: number
  tradeActivity: number
  tradeSpecialization: number
  overseasExpansion: number
  displayMode: GlobeDisplayMode
  showGraticule: boolean
  showRivers: boolean
  showSettlements: boolean
  showMapLabels: boolean
  showRoads: boolean
  showShippingRoutes: boolean
  showCultureBoundaries: boolean
  showReligionBoundaries: boolean
  showHolySites: boolean
  showPoliticalBoundaries: boolean
  showTemperature: boolean
  showMoisture: boolean
  showWind: boolean
  showOceanCurrents: boolean
  showSeaSurfaceTemperature: boolean
  showPrecipitation: boolean
  showFlux: boolean
  showCoastlines: boolean
  showPlateBoundaries: boolean
  wireframe: boolean
  autoRotate: boolean
}

export const DEFAULT_GLOBE_GEN_PARAMS: GlobeGenParams = {
  seed: 2501,
  subdivision: 6,
  planetRadius: 100,
  plateCount: 18,
  continentCount: 5,
  landCoverage: 0.34,
  sizeVariety: 0.55,
  spread: 0.7,
  compactness: 0.5,
  elongation: 0.65,
  coastlineRoughness: 0.7,
  islandCount: 40,
  islandLandShare: 0.1,
  islandClustering: 0.62,
  islandTectonicBias: 0.72,
  mountainStrength: 0.55,
  noiseStrength: 0.65,
  equatorTemperature: 27.5,
  poleTemperature: -15,
  latitudeTemperatureExponent: 3,
  axialTilt: 23.5,
  elevationLapseRate: 6.5,
  temperatureNoiseStrength: 1.5,
  windPerturbation: 0.11,
  oceanCurrentStrength: 0.7,
  oceanHeatTransport: 0.72,
  oceanEvaporation: 0.04,
  landEvaporation: 0.006,
  moistureIterations: 56,
  moistureRetention: 0.97,
  basePrecipitation: 0.016,
  equatorialRainStrength: 0.052,
  subtropicalDryness: 0.55,
  midlatitudeRainStrength: 0.012,
  orographicStrength: 0.55,
  evapotranspirationStrength: 0.38,
  infiltration: 0.1,
  lakeDensity: 0.6,
  lakeMinDepth: 0.008,
  lakeMinRegionCount: 2,
  lakeMinCoastDistance: 2,
  lakeMaxLandCoverage: 0.025,
  lakeEvaporationStrength: 1,
  lakeOverflowThreshold: 1,
  lakeMinFillRatio: 0.18,
  riverBasinThreshold: 0.0015,
  riverMinSourceElevation: 0.25,
  riverMinLength: 3,
  settlementDensity: 1,
  cultureCount: 9,
  culturalBlending: 0.45,
  religionCount: 5,
  religiousProselytism: 0.6,
  polityCount: 6,
  politicalCohesion: 0.55,
  roadDensity: 0.55,
  shippingRouteDensity: 0.55,
  shippingMaxRange: 1.15,
  shippingCurrentInfluence: 0.85,
  shippingWindInfluence: 0.6,
  shippingOpenOceanRisk: 0.25,
  tradeActivity: 0.8,
  tradeSpecialization: 0.55,
  overseasExpansion: 0.55,
  displayMode: 'terrain',
  showGraticule: false,
  showRivers: true,
  showSettlements: false,
  showMapLabels: false,
  showRoads: false,
  showShippingRoutes: false,
  showCultureBoundaries: false,
  showReligionBoundaries: false,
  showHolySites: false,
  showPoliticalBoundaries: false,
  showTemperature: false,
  showMoisture: false,
  showWind: false,
  showOceanCurrents: false,
  showSeaSurfaceTemperature: false,
  showPrecipitation: false,
  showFlux: false,
  showCoastlines: true,
  showPlateBoundaries: false,
  wireframe: false,
  autoRotate: false,
}

export function cloneGlobeGenParams(params: GlobeGenParams): GlobeGenParams {
  return { ...params }
}
